package com.TestSpringBoot.cbs.service;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.*;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.util.Map;

/**
 * SmsService — sends OTP via Fast2SMS Quick SMS API.
 *
 * Fast2SMS API docs: https://docs.fast2sms.com
 * Sign up free at: https://www.fast2sms.com/
 *   → No credit card required
 *   → Free credits on signup for testing
 *   → Works on all Indian mobile numbers immediately
 *
 * API used: Quick SMS (DLT-free, works instantly without template approval)
 *   POST https://www.fast2sms.com/dev/bulkV2
 *   Headers: authorization: <your-api-key>
 *   Body: { route: "q", message: "...", language: "english", flash: 0, numbers: "9876543210" }
 *
 * When fast2sms.enabled=false (dev mode):
 *   - OTP is logged to console only
 *   - verifyOtpWithMsg91() always returns true (DB check is primary)
 *
 * Setup:
 *   1. Sign up at https://www.fast2sms.com/
 *   2. Go to Dev API → Your API Key → copy it
 *   3. Set fast2sms.api.key=<your-key> in application.properties
 *   4. Set fast2sms.enabled=true
 */
@Service
public class SmsService {

    private static final Logger log = LoggerFactory.getLogger(SmsService.class);

    private static final String FAST2SMS_URL = "https://www.fast2sms.com/dev/bulkV2";

    @Value("${fast2sms.enabled:false}")
    private boolean smsEnabled;

    @Value("${fast2sms.api.key:}")
    private String apiKey;

    @Value("${otp.expiry.minutes:10}")
    private int otpExpiryMinutes;

    private final RestTemplate restTemplate = new RestTemplate();

    /**
     * Send OTP to a phone number via Fast2SMS Quick SMS.
     *
     * @param phone the recipient's phone number (10-digit Indian number or +91 format)
     * @param otp   the 6-digit OTP generated by the application
     * @return true if SMS was sent successfully, false on error
     */
    public boolean sendOtp(String phone, int otp) {
        String mobile = normalizePhone(phone);

        if (!smsEnabled) {
            log.info("📱 [DEV MODE - Fast2SMS disabled] OTP for {}: {}", mobile, otp);
            return true;
        }

        try {
            String message = "Your CABkaro OTP is " + otp
                    + ". Valid for " + otpExpiryMinutes + " minutes. Do not share with anyone.";

            // Fast2SMS Quick SMS payload
            Map<String, Object> payload = Map.of(
                    "route",    "q",          // "q" = Quick SMS (no DLT template needed)
                    "message",  message,
                    "language", "english",
                    "flash",    0,
                    "numbers",  mobile        // 10-digit number, no country code
            );

            HttpHeaders headers = new HttpHeaders();
            headers.setContentType(MediaType.APPLICATION_JSON);
            headers.set("authorization", apiKey);  // Fast2SMS uses 'authorization' header

            HttpEntity<Map<String, Object>> request = new HttpEntity<>(payload, headers);

            ResponseEntity<Map> response = restTemplate.exchange(
                    FAST2SMS_URL, HttpMethod.POST, request, Map.class
            );

            if (response.getStatusCode().is2xxSuccessful() && response.getBody() != null) {
                Object returnVal = response.getBody().get("return");
                if (Boolean.TRUE.equals(returnVal) || "true".equalsIgnoreCase(String.valueOf(returnVal))) {
                    log.info("✅ Fast2SMS OTP sent successfully to {}", mobile);
                    return true;
                }
                // Log the full response for debugging
                log.warn("⚠️ Fast2SMS returned non-success for {}: {}", mobile, response.getBody());
                return false;
            }

            log.error("❌ Fast2SMS HTTP error for {} - status {}", mobile, response.getStatusCode());
            return false;

        } catch (Exception e) {
            log.error("❌ Fast2SMS sendOtp error for {}: {}", mobile, e.getMessage());
            return false;
        }
    }

    /**
     * Resend OTP — just calls sendOtp again with a new OTP.
     * Fast2SMS doesn't have a separate resend API; regenerating is sufficient.
     *
     * @param phone     the phone number
     * @param retryType ignored for Fast2SMS (kept for API compatibility)
     */
    public boolean resendOtp(String phone, String retryType) {
        // For Fast2SMS, resend is handled by AuthController regenerating and calling sendOtp.
        // This is a no-op here — just log it.
        log.info("📱 resendOtp called for {} (handled by AuthController)", phone);
        return true;
    }

    /**
     * Optional MSG91-style OTP session verify.
     * Fast2SMS doesn't have a verify-on-server API — OTP verification is handled by
     * comparing with the DB record in AuthController.
     * This method always returns true so the DB check remains the single source of truth.
     *
     * @param phone the phone number
     * @param otp   the OTP to verify
     * @return true always (DB check in AuthController is primary)
     */
    public boolean verifyOtpWithMsg91(String phone, int otp) {
        // Fast2SMS is delivery-only — no server-side OTP session to verify.
        // Verification is entirely handled by the DB expiry + match check in AuthController.
        return true;
    }

    /**
     * Normalize phone to 10-digit Indian format (Fast2SMS requirement).
     * Strips country code (+91 or 91), leading zeros, spaces, dashes.
     *
     * Examples:
     *   +919876543210 → 9876543210
     *   919876543210  → 9876543210
     *   9876543210    → 9876543210
     *   09876543210   → 9876543210
     */
    private String normalizePhone(String phone) {
        if (phone == null) return "";
        String digits = phone.replaceAll("[^\\d]", "");

        // Strip leading 0
        if (digits.startsWith("0")) digits = digits.substring(1);

        // Strip country code 91 (12-digit → 10-digit)
        if (digits.length() == 12 && digits.startsWith("91")) {
            digits = digits.substring(2);
        }
        // Strip country code 91 from 11-digit (e.g. 91xxxxxxxxxx typed with extra digit)
        if (digits.length() == 11 && digits.startsWith("91")) {
            digits = digits.substring(2);
        }

        return digits; // should be 10 digits
    }
}
